### ISSUE TITLE
Not working on Atom 0.169

### ISSUE THREAD

**Issue by DinisCruz** [suda/coffee-navigator#17]
I have an coffee file opened in my editor, and doing this doesn't show the right-hand side navigator:

![image](https://cloud.githubusercontent.com/assets/656739/5710631/a1e71748-9a9b-11e4-9b4a-8761bb062f99.png)

There are no errors shown in the DevTools

Any else I should be trying?

**Comment by suda** [comment]
@DinisCruz I'll try to fix it as soon as possible

**Comment by ramusus** [comment]
Not working in Version 0.176.0 (0.176.0) as well

**Comment by AriaMinaei** [comment]
Same here.

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.0.14

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /c:/Users/Aria/.atom/packages/coffee-navigator/lib/tag-generator.coffee:20

TypeError: Cannot read property '1' of null
  at TagGenerator.module.exports.TagGenerator.parseTagLine (c:\Users\Aria\.atom\packages\coffee-navigator\lib\tag-generator.coffee:13:52)
  at c:\Users\Aria\.atom\packages\coffee-navigator\lib\tag-generator.coffee:60:16
  at Socket.<anonymous> (c:\Users\Aria\AppData\Local\atom\app-0.176.0\resources\app\src\buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

### Commands

```
     -30:50.9 command-palette:toggle (atom-text-editor.editor)
     -30:49.7 core:confirm (atom-text-editor.editor.mini)
     -30:49.6 coffee-navigator:toggle (atom-text-editor.editor)
     -30:19.6 command-palette:toggle (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -30:16.4 core:backspace (atom-text-editor.editor.mini)
     -30:10.4 editor:select-to-first-character-of-line (atom-text-editor.editor.mini)
     -30:07.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -30:07.3 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
coffee-navigator, v0.0.14
emmet, v2.3.2
git-log, v0.2.0
project-manager, v1.15.5

# Dev
No dev packages
```

/cc @atom/core
