### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by laurentpayot** [suda/coffee-navigator#20]
[Enter steps to reproduce below:]

1. Install coffee-navigator package
2. open a coffeescript file in atom

**Atom Version**: 0.176.0
**System**: linux 3.16.0-30-generic
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.0.14

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /home/laurent/.atom/packages/coffee-navigator/lib/tag-generator.coffee:13

TypeError: Cannot read property '1' of null
  at TagGenerator.module.exports.TagGenerator.parseTagLine (/home/laurent/.atom/packages/coffee-navigator/lib/tag-generator.coffee:13:52)
  at /home/laurent/.atom/packages/coffee-navigator/lib/tag-generator.coffee:60:16
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

### Commands

```
     -0:35.7 pane:reopen-closed-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "metrics",
      "symbols-tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffee-navigator, v0.0.14
language-jade, v0.3.0
language-stylus, v0.1.0
linter-coffeelint, v0.1.7
meteor-api, v2.9.0
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by superbizon** [comment]
Windows 7 has the same issue

**Comment by superbizon** [comment]
Atom version 1.4.0

**Comment by kozec** [comment]
Same isue here

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: "Manjaro Linux"
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.0.18

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /data/tom/.atom/packages/coffee-navigator/lib/tag-generator.coffee:13

TypeError: Cannot read property '1' of null
    at TagGenerator.module.exports.TagGenerator.parseTagLine (/data/tom/.atom/packages/coffee-navigator/lib/tag-generator.coffee:13:52)
    at /data/tom/.atom/packages/coffee-navigator/lib/tag-generator.coffee:64:16
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -1:57.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:57.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:57.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:57.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:55.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:54.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:54.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:35.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:33.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:32.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:32.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:26.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:26.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:57.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:49.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:07.3.0 coffee-navigator:toggle (input#coffee-navigator.showOnRightSide.)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "ignoredNames": [
      ".git",
      ".svn",
      "*.pyc"
    ]
  },
  "coffee-navigator": {}
}
```

### Installed Packages

``` coffee
# User
build, v0.55.0
build-make, v0.7.0
coffee-navigator, v0.0.18
color-picker, v2.1.1
tree-ignore, v0.6.1

# Dev
No dev packages
```
