### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by pfzhou** [suda/coffee-navigator#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Unknown Windows Version
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.0.16

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /C:/Users/Leon/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:130

TypeError: undefined is not a function
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.getPath (C:\Users\Leon\.atom\packages\coffee-navigator\lib\coffee-navigator-view.coffee:130:37)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.parseCurrentFile (C:\Users\Leon\.atom\packages\coffee-navigator\lib\coffee-navigator-view.coffee:99:21)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.onActivePaneChange (C:\Users\Leon\.atom\packages\coffee-navigator\lib\coffee-navigator-view.coffee:73:8)
  at C:\Users\Leon\.atom\packages\coffee-navigator\lib\coffee-navigator-view.coffee:20:8
  at Emitter.module.exports.Emitter.emit (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\src\pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\src\pane.js:234:22)
  at Pane.module.exports.Pane.removeItem (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\src\pane.js:368:16)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\src\pane.js:442:16)
  at HTMLDivElement.<anonymous> (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:221:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Leon\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "d:\\source",
    "disabledPackages": [
      "mocha-test-runner",
      "node-debugger",
      "atom-ctags",
      "linter-jshint",
      "linter-coffeelint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.0
atom-typescript, v4.5.9
coffee-navigator, v0.0.16
git-log, v0.4.1
jshint, v1.3.7
linter, v0.12.7
markdown-format, v2.5.1
minimap, v4.9.4

# Dev
No dev packages
```

**Comment by macpham** [comment]
:+1:

**Comment by radkodinev** [comment]
:+1:

**Comment by mscheffel** [comment]
Same Issue on Linux Mint, Atom 1.0.7, Coffee-Navigator 0.0.16...

**Comment by brokenseal** [comment]
:+1:
