### ISSUE TITLE
Failed to activate the coffee-navigator package

### ISSUE THREAD

**Issue by luisalima** [suda/coffee-navigator#28]
[Enter steps to reproduce below:]

1. Try to install coffee-navigator package.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.0.16

### Stack Trace

Failed to activate the coffee-navigator package

```
At undefined is not a function

TypeError: undefined is not a function
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.getPath (/Users/lu/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:130:37)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.parseCurrentFile (/Users/lu/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:99:21)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.onActivePaneChange (/Users/lu/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:73:8)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.initialize (/Users/lu/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:26:6)
  at CoffeeNavigatorView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at CoffeeNavigatorView.ResizableView (/Users/lu/.atom/packages/coffee-navigator/lib/resizable-view.coffee:6:3)
  at new CoffeeNavigatorView (/Users/lu/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:7:3)
  at Object.module.exports.activate (/Users/lu/.atom/packages/coffee-navigator/lib/coffee-navigator.coffee:12:32)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -2:25.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
coffee-navigator, v0.0.16

# Dev
No dev packages
```

**Comment by cgrabowski** [comment]
The package hosted on apm needs to be updated to v0.0.17 because v0.0.16 definitely breaks Atom.  In the meantime I put a soft link in .atom/packages that points to a local copy of the repo.

![screenshot from 2015-06-29 08 01 58](https://cloud.githubusercontent.com/assets/4088332/8407560/c8ca4970-1e35-11e5-9d23-ff6e9304ba98.png)

**Comment by dimatter** [comment]
bump
