### ISSUE TITLE
Failed to load the coffee-navigator package

### ISSUE THREAD

**Issue by bu2** [suda/coffee-navigator#29]
[Enter steps to reproduce below:]
1. Build Atom from source (1.0.4-e187e4b)
2. Clone coffee-navigator and link below ~/.atom/dev/packages
3. Launch Atom in dev mode

**Atom Version**: 1.0.4-e187e4b
**System**: Mac OS X 10.10.4
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.1.0
### Stack Trace

Failed to load the coffee-navigator package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bu2/lab/atom/packages/coffee-navigator/lib/resizable-view.coffee:2:13)
  at Object.<anonymous> (/Users/bu2/lab/atom/packages/coffee-navigator/lib/resizable-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/bu2/lab/atom/myatom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bu2/lab/atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:2:17)
  at Object.<anonymous> (/Users/bu2/lab/atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/bu2/lab/atom/myatom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bu2/lab/atom/packages/coffee-navigator/lib/coffee-navigator.coffee:1:23)
  at Object.<anonymous> (/Users/bu2/lab/atom/packages/coffee-navigator/lib/coffee-navigator.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/bu2/lab/atom/myatom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/package.js:715:34)
  at /Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.enablePackage (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/package-manager.js:141:19)
  at HTMLButtonElement.<anonymous> (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:26 window:toggle-full-screen (atom-pane.pane.active)
     -0:24.3.0 tree-view:toggle (atom-pane.pane.active)
     -0:08.8.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-haml, v0.21.0
linter, v1.2.4
minimap, v4.12.1
node-debugger, v1.1.7

# Dev
coffee-navigator, v0.1.0
```

**Comment by bu2** [comment]
Solved!

I did not know that we need to run a "$ apm install" from the package directory to install dependencies (atom-space-pen-views in that case...).

After installing dependencies and restarting Atom (live reload is not enough), it works !

Regards.
