### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActiveEditor is not a function

### ISSUE THREAD

**Issue by chrisvm** [suda/coffee-navigator#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.4
**Thrown From**: [coffee-navigator](https://github.com/suda/coffee-navigator) package, v0.0.16

### Stack Trace

Uncaught TypeError: atom.workspace.getActiveEditor is not a function

```
At /Users/chrisvm/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:80

TypeError: atom.workspace.getActiveEditor is not a function
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.getPath (/Users/chrisvm/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:130:37)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.parseCurrentFile (/Users/chrisvm/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:99:21)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.onActivePaneChange (/Users/chrisvm/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:73:8)
  at /Users/chrisvm/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:20:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:308:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:279:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:396:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:466:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/chrisvm/GoogleDrive",
    "themes": [
      "nucleus-dark-ui",
      "earthsung-by-jackson-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".idea"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffee-navigator, v0.0.16
earthsung-by-jackson-syntax, v0.3.0
markdown-preview-plus, v2.2.0
minimap, v4.13.4
nucleus-dark-ui, v0.5.12

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
same

**Comment by Vadorequest** [comment]
Same

**Comment by DavidLGoldberg** [comment]
+1

**Comment by DavidLGoldberg** [comment]
Ah, I see the fixes are in master.  Why not do an apm publish patch to fix it?  Can't really be more broken then currently right?

**Comment by DavidLGoldberg** [comment]
Idea / presentation looks great.  Top commit on your package seemed ok (IMO), didn't test it myself.
