### ISSUE TITLE
The sidebar shows nothing

### ISSUE THREAD

**Issue by JevFR** [suda/coffee-navigator#31]
HI !

I've installed this plugin on Atom 1.0.7 for Debian Jessie.

When I run command "coffee-navigator:toggle" with an opened coffee file, the coffee-navigator sidebar appears but stay empty without error.

Furthermore, when i open another coffee file with the coffee-navigator enabled, I can't show it and when i try to close it, the following error is thrown : 

```
/home/kevin/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:130

Stacktrace :

TypeError: undefined is not a function
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.getPath (/home/kevin/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:130:37)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.parseCurrentFile (/home/kevin/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:99:21)
  at CoffeeNavigatorView.module.exports.CoffeeNavigatorView.onActivePaneChange (/home/kevin/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:73:8)
  at /home/kevin/.atom/packages/coffee-navigator/lib/coffee-navigator-view.coffee:20:8
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:306:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:300:19)
  at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app.asar/src/pane.js:271:21)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:388:16)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:458:16)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by spivey3587** [comment]
Yep, same issue for me.  If I use the Command Palette to activate it, the panel is blank.  The hotkey apparently does nothing.

I'm on Atom 1.1.0 running on OSX 10.8.4

Thanks!  I'm looking forward to using this plugin.
